{
    "name": "MU Construction Standard Foundation",
    "summary": "Approved Odoo 19 applications and Egyptian localization bundle",
    "version": "19.0.1.0.1",
    "category": "Services/Project",
    "author": "MU Constructions General",
    "license": "LGPL-3",
    "depends": [
        "crm",
        "sale_management",
        "purchase_stock",
        "stock_account",
        "account_accountant",
        "account_budget",
        "project_enterprise",
        "planning",
        "timesheet_grid",
        "documents",
        "sign",
        "quality_control",
        "maintenance",
        "fleet",
        "industry_fsm",
        "approvals",
        "web_studio",
        "l10n_eg",
        "mu_construction_core",
    ],
    "data": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}
